### ISSUE TITLE
kubectl apply with several resources !

### ISSUE THREAD

**Issue by gdespres** [tazjin/kontemplate#112]
I use kontemplate with several resources.
The runKubectlWithResources() function concatenate all rendered resources.

Only the last one is used by kubectl because each file doesn't start with '---'

I don't know go language but maybe a code like this will solve the issue : 

fmt.Fprintf(stdin, "---\n%s\n", r.Rendered)

**Comment by tazjin** [comment]
See my comment [here](https://github.com/tazjin/kontemplate/pull/113#issuecomment-368050894)
