### ISSUE TITLE
Setting values on the command line

### ISSUE THREAD

**Issue by n0madic** [tazjin/kontemplate#122]
You can add the ability to specify values from the command line? Similar to the --set parameter of Helm.

**Comment by tazjin** [comment]
Hey,

what would you expect the precedence for those options to be? Should they _always_ override whatever is specified declaratively?

Currently we have `variables specified on resource set > imported variables > global varialbes > default.json`.

**Comment by n0madic** [comment]
Yes, they should have the highest priority (as in Helm)

**Comment by tazjin** [comment]
Hmm, I see the point of that. I'm slightly time-constrained for open-source work at the moment though ... it'll be at least a week or two.

Regarding build time IDs: I'm not sure how your setup is organised, but for us all services are organised hierarchically with a `default.json` (note: JSON is supported for default values - and also, JSON is a subset of YAML so you can actually create `.yaml` files containing JSON!) per resource set that contains `version` key.

This key is updated in the repository containing kontemplate code as the final step of every build pipeline using a version of [this script](https://gitlab.com/kontemplate/k8s-update-hook/blob/master/deploy-commit.sh).

In fact that Gitlab organisation linked above contains a (not very well documented) example of how such pipelines could be set up.

**Comment by phillipj** [comment]
Opened https://github.com/tazjin/kontemplate/pull/134 to implement this, any feedback would be much appreciated.
