### ISSUE TITLE
insertFile parameteres or function

### ISSUE THREAD

**Issue by tommyJimmy87** [tazjin/kontemplate#133]
I'd like use the ```insertFile``` function and within the file which i'm including add other functions or  parameters. 

For example i have my config file: 

```
log4j-rolling.properties: |
{{ insertFile "config/log4j-rolling.properties" |indent 12 }}
```
And my log4j-rolling.properties is something like: 

```
log4j.rootLogger={{ passLookup (print  "something"  ) | cat }}, stdout
```

Is it possible or there's some limitation with the function ?

**Comment by tazjin** [comment]
You can't currently do this in one pass, `insertFile` will not template files - it only inserts their contents.

I think that the recent PR from Nokia was about a similar case and they opted for doing the templating in two steps instead, you may want to read up on the conversation here: #125

**Comment by tommyJimmy87** [comment]
Uhm, yes probably this could be a good workaround.
