### ISSUE TITLE
Allow specifying the kubectl executable

### ISSUE THREAD

**Issue by elyezer** [tazjin/kontemplate#143]
By doing that kontemplate could also apply the templates using the open shift origin client. Open shift origin client's executable is called `oc` and also offers the apply with `-f` and `--dry-run`.

**Comment by tazjin** [comment]
This makes sense and will go in the next release!

**Comment by elyezer** [comment]
Thank *you*, I am glad you liked the suggestion.

**Comment by tazjin** [comment]
@elyezer This is now in `master` and will be in 1.7.0 once we figure out the discussion in #142 :)

**Comment by elyezer** [comment]
Excellent! Thank you for getting this done.
