### ISSUE TITLE
[Feature] Ability to exclude some resources (or files) from template processing

### ISSUE THREAD

**Issue by merlineus** [tazjin/kontemplate#149]
This is not an issue, but an improvement suggestion.

Some Kubernetes ConfigMap manifests can contain "{{}}" blocks which are interpreted as templates by Kontemplate and lead to manifest processing errors. For example prometheus-operator [addon](https://github.com/kubernetes/kops/blob/master/addons/prometheus-operator/v0.19.0.yaml) for kops. 

So maybe ability to exclude some manifests from template processing will be a good feature :)

**Comment by vlevitskiy-gemicle** [comment]
+1

@merlineus how u solve this now? Thanks for the answer.

**Comment by vlevitskiy-gemicle** [comment]
Temp solution is to escape it like
{{`{{Your.Data}}`}}

**Comment by tazjin** [comment]
Interesting, my gut feeling is that escaping should probably be used (like @vlevitskiy-gemicle demonstrated above) but that would probably get ugly for files containing lots of these templates.

**Comment by merlineus** [comment]
@vlevitskiy-gemicle the only way I've found is escaping, but it's ugly and boring :)
For example, there are about 50 occurrences in the specified kops addon. Also it's harder to track changes in files.

**Comment by tazjin** [comment]
The source of kontemplate is moving to [git.tazj.in](https://git.tazj.in/tree/ops/kontemplate) and I've moved this issue to the depot@tazj.in mailing list [over here](https://groups.google.com/a/tazj.in/forum/?hl=en#!topic/depot/huXvKsi-rsE).
