### ISSUE TITLE
A way to apply config with options (--as-admin, --as-group)

### ISSUE THREAD

**Issue by theneva** [tazjin/kontemplate#157]
I'm [setting up Prometheus to work with Google Kubernetes Engine](https://cloud.google.com/monitoring/kubernetes-engine/prometheus). Part of the setup requires applying some role-based access control configuration that must be applied with `--as-admin` and `--as-group=system:masters`.

As far as I can tell, there is no way to specify options to pass on to `kubectl`.

I would like to be able to specify an optional field `options` (or something more appropriate) in the [Resource Set configuration](https://github.com/tazjin/kontemplate/blob/5f433c46c16f4466ad17578eb1762399aa7746d1/docs/resource-sets.md) which would be forwarded to `kubectl` for `kubectl`-wrapping commands, and which might look like:

```yaml
options: "--as-admin --as-group=system:masters"
```

or:

```yaml
options:
  - --as-admin
  - --as-group=system:masters
```

Would it be possible to support something like this, or is it outside the scope of "extremely simple"?

**Comment by tazjin** [comment]
That would be possible to support! You're saying you would like this to happen per individual resource set, right?

IIRC we actually already do separate `kubectl` invocations, so that shouldn't be too hard.

**Comment by theneva** [comment]
Yep! I don't want every single resource set to be applied as admin.

This doesn't sound too hard, then. I'll take a crack at it tomorrow :smile:
