### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by tpo** [tazjin/kontemplate#170]
Hello Vincent,

kontemplate is excellent, thanks a lot :-)!!!

As my usage of kontemplate is advancing I today have used the `insertTemplate` function.

The result was:

```
kontemplate: error: Error templating resource sets: Could not load template Res.yaml: template: Res.yaml:9: function "insertTemplate" not defined
```

Since I'm using kontemplate's github page a lot for my documentation needs I was perplexed and thought that maybe I'm using insertTemplate in a wrong way. It took me a while to realize that I was using the [release](https://github.com/tazjin/kontemplate/releases/tag/v1.7.0) version of kontemplate, that in fact does not have the `insertTemplate` function/feature yet.

So I'd suggest that if you do not mind, please trigger a release, to have that nice feature included in a released build of kontemplate. That'd be very nice.

Again, thanks a lot for the very nice tool!
*t

**Comment by tazjin** [comment]
Hey, version 1.8.0 [is now released](https://github.com/tazjin/kontemplate/releases/tag/v1.8.0).

**Comment by tpo** [comment]
On Wed, 4 Sep 2019, Vincent Ambo wrote:

> Hey, version 1.8.0 is now released.

:-) !!!

Thanks a lot Vincent for your wonderful tool :-) !
*t
