### ISSUE TITLE
Add support for null checks

### ISSUE THREAD

**Issue by juanjoDiaz** [tazjin/kontemplate#175]
YAML supports null (https://yaml.org/type/null.html).

It should be possible to do null checks like `{{ if eq .myVar null }}`.

**Comment by tazjin** [comment]
The code inside of template pipelines will refer to Go types and values, so you probably want `== nil` (where `nil` is what Go calls `null`).

Please note that the source of kontemplate is moving to [git.tazj.in](https://git.tazj.in/tree/ops/kontemplate) and issues should now be reported to the [mailing list](https://groups.google.com/a/tazj.in/forum/?hl=en#!forum/depot). Feel free to email depot@tazj.in if you need to follow up on this!
