### ISSUE TITLE
Template function for hashing things from k8s?

### ISSUE THREAD

**Issue by tazjin** [tazjin/kontemplate#45]
An idea that struck me and that may be silly!

It could be interesting to have a template function like `resourceHash :: ResourceType -> ResourceName -> Hash` (e.g. `{{ resourceHash "ConfigMap" "app-config" }}`).

This could be used to detect changes to resources that should trigger rolling-updates and such where Kubernetes does not currently provide [native support](https://github.com/kubernetes/kubernetes/issues/22368) for doing that.

### Example use-case:

Someone using the [letsencrypt-controller](https://github.com/tazjin/kubernetes-letsencrypt) gets a new `Secret` after the controller refreshed the certificate before it expires.

Some `backend-service` or Nginx deployment  should now be rolling updated to pick up the new certificate. With this `resourceHash` function the user could write something like this in kontemplate:

```
annotations:
  secretHash: {{ resourceHash "Secret" "my-website-tls" }}
```

and on the next run it would be updated.

### Implementation thoughts

Under the hood this should basically do a `kubectl get --export -o json --context $context <resourcetype> <name> | sha256sum`.

I think this *may* be useful but haven't quite figured it out yet. Keeping this issue around so I don't forget.

### Caveats

* Does not happen immediately after resources change (fine for letsencrypt-certs for example as there is a certain grace period with my controller)
* Does not work in `template` mode (in template mode we can not call `kubectl`, that would be against the rules)

**Comment by norbertkeri** [comment]
This is already possible if the resource you are referring to is a standalone file, eg. in your deployment you can do:

```yaml
  annotations:
    configmap/checksum: {{ insertFile "./configmap.yaml" | sha256sum }}
```

**Comment by tazjin** [comment]
I'm closing this issue as I'm not currently planning to work on it. Please note that the source of kontemplate is moving and issue tracking / patches will be available on [depot@tazj.in](https://groups.google.com/a/tazj.in/forum/?hl=en#!forum/depot).
