### ISSUE TITLE
Document valid format for variable names

### ISSUE THREAD

**Issue by samiralajmovic** [tazjin/kontemplate#68]
Seems camelCasing / PascalCasing / snake_casing is supported but not lisp-case(hello_world). Would be nice if it said in the documentation what casing is supported and preferably throw an explanatory error when user uses lisp-case.

**Comment by tazjin** [comment]
Hey!

The templating engine is the one from [Go itself](https://golang.org/pkg/text/template/). I'll see if there are docs on what sorts of namings it suggests, but I don't think I can do much about the errors that it throws without first performing a lot of custom validation.

Thanks for filing the issue :-)

**Comment by samiralajmovic** [comment]
Ah cheers. Yeah I reckoned it was from Go. Still like you mentioned, it would be nice just to have it somewhere in the documentation so users are aware, since

```yaml
  template:
    metadata:
      labels:
        lala-lala: lala
```

is valid yaml, and k8s seems to allow it with the flag --dry-run.

**Comment by tazjin** [comment]
That should work fine though, you can have lisp-case in the output just not in the names of the (user-defined) variables.
