### ISSUE TITLE
Rewrite project in a sane language (Rust!)

### ISSUE THREAD

**Issue by tazjin** [tazjin/kontemplate#72]
**Old issue text below the line!**

I can't defend (mostly to myself) maintaining a Go project anymore and it's time to go for the Rust rewrite.

[Milestone 6](https://github.com/tazjin/kontemplate/milestone/6) will track the progress of the rewrite. Some choices that have been made:

* Compatibility with existing configuration files **will** be kept
* Compatibility with existing template files **will not** be kept
* Templating will not be restricted to just JSON/YAML files

This issue stays open until the milestone is resolved.
 
------------

Preferably Rust.

Either way, I'd like to not break compatibility with existing setups which means I have to re-implement Go's templates in whatever I choose.

Doing this in Rust could contribute some useful things to the Rust ecosystem I suppose.

Note: This is mostly for my own sanity.

**Comment by phillipj** [comment]
Care to elaborate what's bothering you with Go? ..or point to some related blogs or similar.

**Comment by tazjin** [comment]
Sure, I'm not writing it all down again but here is a list of lists of problems with Go: [Go is not good](https://github.com/ksimka/go-is-not-good)
