### ISSUE TITLE
Allow default yaml files to have the .yml extension

### ISSUE THREAD

**Issue by mazzus** [tazjin/kontemplate#83]
Kontemplate seems to accept the .yml extension for most files, but not for the files used to specify default values.

**Comment by tazjin** [comment]
That sounds like a bug, I'll check it out. Thanks for reporting!

**Comment by tazjin** [comment]
Fixed in master, but it'll be a few days before I cut a new release!

**Comment by mazzus** [comment]
Thanks for fixing it so fast!
